//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class EColliderWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(ECollider));
		L.RegVar("None", get_None, null);
		L.RegVar("Normal", get_Normal, null);
		L.RegVar("WithBg", get_WithBg, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, ECollider.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Normal(IntPtr L)
	{
		ToLua.Push(L, ECollider.Normal);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WithBg(IntPtr L)
	{
		ToLua.Push(L, ECollider.WithBg);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		ECollider o = (ECollider)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

