//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class NetCore_VarintStreamWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(NetCore.VarintStream), typeof(NetCore.ByteStream));
		L.RegFunction("readVarint8", readVarint8);
		L.RegFunction("writeVarint8", writeVarint8);
		L.RegFunction("readVarint16", readVarint16);
		L.RegFunction("writeVarint16", writeVarint16);
		L.RegFunction("readVarint32", readVarint32);
		L.RegFunction("writeVarint32", writeVarint32);
		L.RegFunction("readVarintString", readVarintString);
		L.RegFunction("writeVarintString", writeVarintString);
		L.RegFunction("New", _CreateNetCore_VarintStream);
		L.RegFunction("__tostring", Lua_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateNetCore_VarintStream(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				NetCore.VarintStream obj = new NetCore.VarintStream();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: NetCore.VarintStream.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readVarint8(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetCore.VarintStream obj = (NetCore.VarintStream)ToLua.CheckObject(L, 1, typeof(NetCore.VarintStream));
			byte o = obj.readVarint8();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int writeVarint8(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			NetCore.VarintStream obj = (NetCore.VarintStream)ToLua.CheckObject(L, 1, typeof(NetCore.VarintStream));
			byte arg0 = (byte)LuaDLL.luaL_checknumber(L, 2);
			obj.writeVarint8(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readVarint16(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetCore.VarintStream obj = (NetCore.VarintStream)ToLua.CheckObject(L, 1, typeof(NetCore.VarintStream));
			short o = obj.readVarint16();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int writeVarint16(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			NetCore.VarintStream obj = (NetCore.VarintStream)ToLua.CheckObject(L, 1, typeof(NetCore.VarintStream));
			short arg0 = (short)LuaDLL.luaL_checknumber(L, 2);
			obj.writeVarint16(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readVarint32(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetCore.VarintStream obj = (NetCore.VarintStream)ToLua.CheckObject(L, 1, typeof(NetCore.VarintStream));
			int o = obj.readVarint32();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int writeVarint32(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			NetCore.VarintStream obj = (NetCore.VarintStream)ToLua.CheckObject(L, 1, typeof(NetCore.VarintStream));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.writeVarint32(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readVarintString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetCore.VarintStream obj = (NetCore.VarintStream)ToLua.CheckObject(L, 1, typeof(NetCore.VarintStream));
			string o = obj.readVarintString();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int writeVarintString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			NetCore.VarintStream obj = (NetCore.VarintStream)ToLua.CheckObject(L, 1, typeof(NetCore.VarintStream));
			string arg0 = ToLua.CheckString(L, 2);
			obj.writeVarintString(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}
}

